### PR TITLE
Add documentation on how to add a new plugin

### PR DESCRIPTION
**Pull request by sevenmachines**

### CODE REVIEW

**Comment by sevenmachines** [comment]
@KrisSaxton @filipposc5 This should be OK-ish docs for the first part of adding plugins to graphite. If you want to run through it and fix anything, fill in the blanks etc?

**Comment by filipposc5** [comment]
Thanks @niallcreech, will run through it today

**Comment by sevenmachines** [comment]
Cool, I expect to have missed out stuff and poorly put words into sentences ordered so happily pad it out as you go

**Comment by lukaszraczylo** [comment]
conflicts here @niallcreech

**Comment by sevenmachines** [comment]
@lukaszraczylo rebased

**Comment by lukaszraczylo** [comment]
ta :)

**Pull request merged**
